# Generated by Django 3.1.3 on 2020-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('estimated_time', models.IntegerField()),
                ('worked_time', models.IntegerField()),
            ],
        ),
    ]
