# Generated by Django 3.1.3 on 2020-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201128_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='remaining_time',
            field=models.FloatField(default=0.0),
        ),
    ]
